Fix issue where From_Utf8 was raising an exception.
AdaCore/aws pull request #194
Opened 2021-01-28 16:52 UTC by TurboGit

Some characters don't have an equivalence from Utf8 to 8bits. In
this case we fallback by default to a space character to avoid
the exception. A callback is also put in place to let user's propose
some equivalence better the Utf8 character and 8bit one. For example
in Utf8 there is different left and right apostrophe, one can
use the standard 8bit quote in place.

For U127-049.

2021-01-28 17:30 UTC, anisimkov reviewed
Why is it space, Maybe the question mark is better ? I saw the '?' when unable to decode wide char somewhere,

2021-01-28 17:37 UTC, TurboGit commented
> Why is it space, Maybe the question mark is better ? I saw the '?' when unable to decode wide char somewhere,

Good point indeed, probably better will do that. Thanks.

2021-01-28 21:08 UTC, anisimkov requested changes
comment next to Set_Utf8_Mapping

2021-01-28 22:10 UTC, TurboGit commented
> comment next to Set_Utf8_Mapping
> This routine can be useD

Fixed, thanks!

2021-01-29 03:03 UTC, anisimkov approved these changes

2021-01-29 07:37 UTC, merged