Fix connection flow control
AdaCore/aws pull request #263
Opened 2021-10-08 13:46 UTC by anisimkov

Do not need update connection flow control together with stream
flow control. Connection flow control has to be updated separately.
Fixes file dowmload longer than 2G.

TN: S507-051

2021-10-10 16:50 UTC, TurboGit requested changes
Just two minor comments, look ok otherwise!

2021-10-10 16:50 UTC, TurboGit commented on src/http2/aws-http2-frame.ads
> +   procedure Dump_Binary (Data : Stream_Element_Array);
to be moved in AWS.Utils as generic.

2021-10-10 16:50 UTC, TurboGit commented on src/core/aws-client-http_utils.adb
> +      Frame : constant HTTP2.Frame.Object'Class :=
indent :

2021-10-11 03:59 UTC, anisimkov commented on src/core/aws-client-http_utils.adb
> +      Frame : constant HTTP2.Frame.Object'Class :=
Moved

2021-10-11 04:03 UTC, anisimkov commented on src/http2/aws-http2-frame.ads
> +   procedure Dump_Binary (Data : Stream_Element_Array);
Moved

2021-10-11 10:09 UTC, merged